### ISSUE TITLE
CW3 - 10 variant

### ISSUE THREAD

**Issue by WeisseKatze** [oleksandrblazhko/ai181-lavrenova#14]
У документі Топ-10 OWASP 2017 надано рекомендації для організації по впровадженню програми забезпечення безпеки програмних продуктів. Аргументовано перерахуйте сім рекомендацій в порядку убування їх значущості (рівня впливу) на безпеку програмних продуктів.

1. Аналізуйте дані, отримані від заходів із впровадження та перевірки, щоб знайти першопричину та закономірності вразливості, щоб стимулювати стратегічні та системні вдосконалення на підприємстві. Вчіться на помилках і пропонуйте позитивні стимули для просування вдосконалень. (Для успішного функціонування програми забезпечення безпеки програмних продуктів необхідно аналізувати дані цих практик для їх покращення)
2. Керуйте за допомогою показників. Приймайте рішення про покращення та фінансування на основі отриманих показників і даних аналізу. Показники включають дотримання практик безпеки/діяльності, введені вразливості, пом’якшені вразливості, охоплення програми, щільність дефектів за типом і випадком підрахунків та ін (Для якісного аналізу практик необхідно мати встановлені міри показників, які можна порівнювати, наприклад у вигляді рейтингових оцінок)
3. Визначте та інтегруйте дії щодо безпечного впровадження та перевірки в існуючі процеси розробки та експлуатації. Діяльність включає моделювання загроз, безпечне проектування та перевірку, безпечне кодування та перевірку коду, тестування на проникнення та виправлення. (Важливо моделювати можливі загрози та дії щодо їх усунення на різних етапах розробки та експлуатації)
4. Встановіть набір цілеспрямованих політик і стандартів, які забезпечують базовий рівень безпеки застосунків для всіх команд розробників. (Усі застосунки повинні володіти базовим рівнем безпеки)
5. Визначте потреби захисту застосунку з точки зору бізнесу. Це має частково регулюватися законами про конфіденційність та іншими нормативними актами, пов’язаними з активом даних, що захищається. (Кожна предметна область має свої обмеження щодо конфіденційності даних, це треба враховувати при розробці)
6. Створіть програму безпеки застосунків і стимулюйте впровадження. (Важливо мати дорожню карту з впровадження безпеки застосунків на кожному етапі життєвого циклу ПЗ)
7. Документуйте всі застосунки та пов’язані з ними ресурси даних. Більші організації повинні розглянути впровадження бази даних керування конфігурацією (CMDB) для цієї мети.

**Comment by oleksandrblazhko** [comment]
оцінка = 2 бали
