### ISSUE TITLE
CW4 - 10 variant

### ISSUE THREAD

**Issue by WeisseKatze** [oleksandrblazhko/ai181-lavrenova#17]
Серед п'яти бізнес-функцій SAMM-моделі можна виділити такі як верифікація (Verification) та операції (Operations). 
Покажіть можливі логічні зв'язки між завданнями, які пропонують три практики безпеки
першої функції та три практики безпеки другої функцій.

Практика «Оцінка архітектури» та практика «Управління інцидентами» доповнюють одна одну в питаннях виявлення таких вразливостей як : авторизація, несанкціонована зміна даних. Для виявлення слабких місць в архітектурі використовується практика «Оцінка архітектури»,  для забезпечення своєчасного виявлення та адекватної відповіді на загрози використовують практику «Управління інцидентами».

Оскільки на протязі життєвого циклу ПЗ використовуються постійно нові версії технологічного стеку, чиї вразливості також змінюються, практика «Управління середовищем» націлена на підтримку безпеки використовуваних технологій. Із використанням нових технологій варто пересвідчитись, що виконуються усі функціональні вимоги, це досягається шляхом виконання практики «Тестування на основі вимог».

Для надійного розгортання системи варто передбачити можливі проблеми із операційними системами та резервними сховищами даних, для цього треба керуватися практикою «Оперативне управління». Для ретельного тестування обраних тактик, щодо підтримки надійного розгортання системи - використовуємо практику «Тестування безпеки»

**Comment by oleksandrblazhko** [comment]
Оцінка = 2 бали.
Дякую!
