### ISSUE TITLE
CW6-Variant 10

### ISSUE THREAD

**Issue by WeisseKatze** [oleksandrblazhko/ai181-lavrenova#25]
Запитання 1: Припустимо, що необхідно забезпечити доступ до БД, враховуючи, що:
- кількість таблиць = 10 * 3 = 30;
- кількість користувачів = 10 * 4 = 40;
- кількість груп (ролей) користувачів = 10 * 2 = 20

1)
   Трудомісткість операцій для DAC-керуванням доступом = 30*40=1200
   Трудомісткість операцій для RBAC-керуванням доступом = 40*20+20*30=1400
   Трудомісткість операцій для MAC-керуванням доступом = 40+30=70

   Не доцільно переходити з моделі DAC на RBAC, оскільки трудомісткість операцій зростає.
   Доцільно перейти з моделі RBAC на MAC, оскільки трудомісткість операцій значно зменшується.
2) Якщо кількість користувачів збільшити удвічі 40*2=80, а кількість груп зменшити у 2 рази 20/2=10, то

-    Трудомісткість операцій для DAC-керуванням доступом = 30*80=2400
-    Трудомісткість операцій для RBAC-керуванням доступом = 80*10+10*30=1100
-    Трудомісткість операцій для MAC-керуванням доступом = 80+30=110

   В нових умовах доцільно переходити з моделі DAC на RBAC, оскільки трудомісткість операцій зменшується та доцільно перейти з моделі RBAC на MAC, оскільки трудомісткість операцій значно зменшується.

3) Порівнюючи пункти 1 та 2, можна зробити висновок, що при збільшенні кількості користувачів та зменшенні кількості груп керування доступом ускладнюється для моделей DAC та MAC, та полегшується для моделі RBAC. Тому моделі DAC та MAC доцільніше використовувати для БД з меншою кількістю користувачів та більшою кількістю груп, а модель RBAC навпаки доцільніше використовувати для БД з більшою кількістю користувачів та меншою кількістю груп.

Запитання 2:
1) Програмне забезпечення, яке було розглянуто в лабораторній роботі #1, містить БД, яка має наступну структуру:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/52915030/207819401-80d88efb-704b-4f52-96ca-ee0a3d097421.png">
Користувачами ПЗ є працівники медзакладу, які поділяються на наступні групи:

- лікар-клініцист
- лікар лабораторної / інструментальної діагностики
- відділ реєстратури
- адміністратор

2) Програмне забезпечення працює за моделю RBAC. Програмно ця модель була забезпечена за допомогою створення ролей у Django-проєкті та наданні окремих Permissions, кожній групі, щодо доступу до модулів ПЗ та дозволів на читання/редагування/видалення даних з БД.
3) Якщо кількість користувачів та можливих груп (ролей) користувачів зросте в 100 разів, на мій погляд, доцільно залишити модель керування доступом RBAC, оскільки вона підходить для систем, в яких кількість користувачів набагато більша за кількість груп.
4) Припустимо, що замовник програмного забезпечення вніс додаткову вимогу із впровадження MAC-моделі керування доступом, рекомендації стосовно визначення рівнів доступу для суб’єктів та міток конфіденційності для об’єктів, які можуть використовуватися оновленим програмним забезпеченням будуть наступними:

- для Адміністратора al = 3
- для лікарів al = 2
- для реєстратури al = 1
- для таблиць «Обстеження», «Лабораторний аналіз», «Інструментальний аналіз», «Симптом», «Діагноз» cs = 2
- для таблиць «Пацієнт», «Лікар»  cs = 1

**Comment by oleksandrblazhko** [comment]
Оцінка = 7 балів
