### ISSUE TITLE
CW7-Variant 10

### ISSUE THREAD

**Issue by WeisseKatze** [oleksandrblazhko/ai181-lavrenova#28]
Запитання № 1:
Опишіть ПЗ, в якому знайдено вразливість:
- назва ПЗ, URL-посилання в інтернеті (знайти через пошукову систему);
   MonikaBrzica scm, https://github.com/MonikaBrzica/scm
- призначення ПЗ та приклади споживачів, які можуть бути зацікавлені у використанні ПЗ;
   Система управління ланцюгами поставок (SCM-система) — прикладне програмне забезпечення, призначене для автоматизації та управління всіма етапами постачання підприємства і для контролю за весь рух товарів: закупівля сировини і матеріалів, виробництво, розповсюдження продукції. У використанні такого ПЗ зацікавлені підприємства логістичних і виробничих процесів, наприклад, заводи харчових продуктів, меблеві фабрики, тощо. 

Запитання № 2:
Опишіть знайдену вразливість , переклавшу на українську розділ Description.

У MonikaBrzica scm виявлено вразливість, класифіковану як критичну. Це стосується невідомої частини файлу uredi_korisnika.php. Маніпуляції з аргументом id призводять до sql-ін'єкції. Ініціювати атаку можна віддалено. Експлойт був відкритий для громадськості та може бути використаний. Пов’язаний ідентифікатор цієї вразливості – VDB-213699.

Запитання № 3:
Наведіть фрагменти прикладів уразливого програмного коду, розглянувши розділ References to Advisories, Solutions, and Tools.

1. CWE-89: Неправильна нейтралізація спеціальних елементів, що використовуються в команді SQL ("Впровадження SQL") <p> Наступний код динамічно створює та виконує SQL-запит, який шукає елементи, що відповідають вказаному імені. Запит обмежує відображувані елементи тими, у яких власник збігається з іменем користувача поточного автентифікованого користувача.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/52915030/209312203-5ab0d0c8-91f2-4885-88aa-ead905af1a81.png"> </p> <p> Цей код має намір надрукувати підсумок повідомлення з ідентифікатором повідомлення. 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/52915030/209312643-1be61c20-d63e-4a56-9fd6-b4f690a70577.png"></p>
2. CWE-74: Неналежна нейтралізація спеціальних елементів у вихідних даних, що використовуються нижчим компонентом («Ін’єкція») <p>Цей приклад коду має на меті взяти ім’я користувача та перерахувати вміст домашнього каталогу цього користувача. 
<img width="241" alt="image" src="https://user-images.githubusercontent.com/52915030/209312987-564f5d0e-d7a8-4287-879e-d11f0ef6e33f.png"> </p> <p> Розглянемо наступну програму. Він має намір виконати "ls -l" для імені вхідного файлу. Підпрограма validate_name() виконує перевірку вхідних даних, щоб переконатися, що дозволені лише буквено-цифрові символи та символи «-», що дозволяє уникнути недоліків проходження шляху (CWE-22) і впровадження команд ОС (CWE-78). Дозволяються лише такі імена файлів, як "abc" або "d-e-f".
<img width="242" alt="image" src="https://user-images.githubusercontent.com/52915030/209313172-355a1933-f3ff-491e-90b9-46bc2aa9feb6.png"></p>

Запитання № 4:
Розглянувши приклад публікації, номер якої співпадає з номером вашого варіанту виконання лабораторних робіт, перекладіть української вказані назви розділи.
**Вступ**
У додатках, що інтенсивно працюють з даними, досить часто код реалізації динамічно створює рядки запитів до бази даних і виконує їх. Наприклад, типова веб-служба сервлетів Java створює рядки запитів SQL і надсилає їх через з’єднувач JDBC до SQL-сумісної бази даних. Програміст сервлетів насолоджується статичною перевіркою за допомогою системи стійких типів Java. Однак система типів Java робить мало для перевірки можливих помилок у динамічно згенерованих рядках запиту SQL. Наприклад, помилка типу в створеному запиті на вибір (наприклад, порівняння атрибута рядка з цілим числом) може призвести до виняткової ситуації під час виконання SQL. Наразі такі дефекти мають бути викорінені шляхом ретельного тестування, або (що ще гірше) клієнти можуть виявити їх під час виконання. У цій статті ми описуємо JDBC Checker, надійний інструмент статичного аналізу для перевірки правильності динамічно згенерованих рядків запиту. Ми успішно застосували інструмент для пошуку відомих і невідомих дефектів у реалістичних програмах за допомогою JDBC. У цій статті ми надаємо короткий опис нашого інструменту
Ми використовуємо конкретний приклад, щоб пояснити нашу техніку аналізу. Припустімо, що програміст розробляє зовнішню програму сервлетів для серверної бази даних, керованої SQL. Програма є частиною системи продуктового магазину, і в базі даних є таблиця INVENTORY, що містить список усіх товарів у магазині. Ця таблиця містить три стовпці: РОЗДРІБНИЙ ПРОДАЖ, ОПТОВИЙ ПРОДАЖ і ТИП, серед інших. Стовпці РОЗДРІБНИЙ та ОПТОВИЙ ПРОДАЖ мають цілий тип і вказують відповідні грошові значення в центах. Стовпець TYPE також має цілий тип і представляє коди типів продуктів для елементів у таблиці. У базі даних продуктового магазину є ще одна таблиця TYPES, яка використовується для пошуку кодів типів. Ця таблиця містить стовпці TYPECODE, TYPEDESC і NAME відповідно типів integer, varchar (рядок) і varchar.
Наступний приклад фрагмента коду ілюструє деякі поширені помилки, які програмісти можуть зробити під час програмування додатків сервлетів Java:
`ResultSet getPerishablePrices(String lowerBound) { String query = "SELECT ’$’ || " + "(RETAIL/100) FROM INVENTORY " + "WHERE "; if (lowerBound != null) { query += "WHOLESALE > " + lowerBound + " AND "; } query += "TYPE IN (" + getPerishableTypeCode() + ");"; 
return statement.executeQuery(query); } 
String getPerishableTypeCode() { return "SELECT TYPECODE, TYPEDESC FROM TYPES " + "WHERE NAME = ’fish’ OR NAME = ’meat’";`

У цьому прикладі може виникнути кілька різних помилок виконання (жодна з цих помилок не буде виявлена системою типів Java):
(1) Вираз `’$’ || (RETAIL/100) об’єднує символ «$»` із результатом числового виразу RETAIL/100.
(2) У виразі `WHOLESALE > lowerBound` стовпець WHOLESALE типу integer порівнюється з lowerBound, який оголошується як рядок. Це ризиковано, тому що ніщо (зокрема, не сама система типів Java) не заважає рядковій змінній lowerBound містити нечислові символи.
(3) Рядок, повернутий методом `getPerishableTypeCode(),` є підзапитом, який вибирає два стовпці з таблиці TYPES. Оскільки пропозиція IN SQL підтримує лише підзапити, що повертають один стовпець, виникне помилка виконання

Бази даних, які отримують ці запити SQL, звичайно, виконують синтаксичну та семантичну перевірку запитів. Але оскільки ці запити генеруються динамічно, будь-які помилки, виявлені базою даних, повідомляються під час виконання. Ці помилки хотілося б виловлювати статично у вихідному коді. Наш інструмент, JDBC Checker, є інструментом статичного аналізу, який використовується для позначення потенційних помилок або перевірки їх відсутності в динамічно створених запитах SQL. Наш підхід поєднує добре відомі теоретико-автоматні методи та варіант проблеми досяжності контекстно-вільної мови (CFL) [3]. На рисунку 1 наведено схему архітектури нашого інструменту. Наш аналіз складається з двох основних етапів. На першому кроці ми створюємо автомат із кінцевим станом, який консервативно наближає набір рядків SQL, використовуючи техніку [1]. Це дає FSA, який фіксує набір можливих рядків SQL. Потім ми попередньо обробляємо автомат для створення орієнтованого графа, позначеного ключовими словами, примітивами та літералами SQL. На другому кроці ми застосовуємо CFL-досяжність для виконання семантичної перевірки об’єктних програм. Одне застосування CFL-досяжності використовується для пошуку контексту введення та інформації про обсяг. Після цього слід друге застосування CFL-досяжності для виконання перевірки типу згенерованих програм, розглядаючи систему типів SQL як контекстно-вільну мову. У разі виявлення семантичних помилок повідомляється під час обох фаз. Варто відзначити головну відмінність нашого аналізу від традиційного аналізу, такого як перевірка типу SQL. У стандартних налаштуваннях один запит аналізується під час виконання, тоді як ми статично аналізуємо потенційно нескінченний набір запитів. Наш аналіз надійний у тому сенсі, що він не пропускає жодних помилок, які ми перевіряємо, і якщо він не знаходить жодних помилок, то гарантовано, що такі помилки не виникають під час виконання. Перегляньте [2] для більш детального опису нашої методики аналізу, експериментальних результатів та обговорення пов’язаної роботи.
<p> <img width="465" alt="image" src="https://user-images.githubusercontent.com/52915030/209315588-dedac048-10fa-4434-8bb1-2e726c4cb236.png"> </p> Рисунок 1 - Схема аналізу

**Comment by oleksandrblazhko** [comment]
Оцінка = 7 балів.
Дякую за активність!
