### ISSUE TITLE
CW8 - Variant 10

### ISSUE THREAD

**Issue by WeisseKatze** [oleksandrblazhko/ai181-lavrenova#31]
### Запитання №1.1
Опишіть ПЗ або програму бібліотеку, в яких знайдено вразливість:

- назва ПЗ або програмної бібліотеки, URL-посилання в інтернеті (знайти через пошукову систему): **Cisco AnyConnect VPN https://www.cisco.com/c/en_be/products/security/anyconnect-secure-mobility-client/index.html**

- призначення ПЗ або програмної бібліотеки та приклади споживачів, які можуть бути зацікавлені у їх використанні: **Надає співробітникам компаній можливість працювати будь-де з будь-якого місця, на корпоративних ноутбуках або персональних мобільних пристроях у будь-який час. AnyConnect спрощує безпечний доступ до кінцевої точки та забезпечує безпеку, необхідну для забезпечення безпеки та захисту організації. Цим ПЗ користуються великі корпорації з різних галузей, які потребують мати доступ до корпоративного ПЗ, наприклад ІТ, охорона здоров'я, фінансові структури, заклади вищої освіти, уряд, тощо**

### Запитання №1.2
Опишіть знайдену вразливість , переклавшу на українську мову розділ Description.

**Уразливість у VPN-сервері Cisco AnyConnect пристроїв Cisco Meraki MX і Cisco Meraki Z3 Teleworker Gateway може дозволити неавтентифікованому віддаленому зловмиснику викликати стан відмови в обслуговуванні (DoS) на ураженому пристрої. Ця вразливість пов’язана з недостатньою перевіркою наданих клієнтом параметрів під час встановлення сеансу SSL VPN. Зловмисник може використати цю вразливість, створивши зловмисний запит і надіславши його на уражений пристрій. Успішний експлойт може дозволити зловмиснику спричинити збій і перезапуск сервера Cisco AnyConnect VPN, що призведе до збою встановлених з’єднань SSL VPN і змусить віддалених користувачів ініціювати нове з’єднання VPN і повторно автентифікуватися. Тривала атака може перешкодити встановленню нових з’єднань SSL VPN. Примітка. Коли трафік атаки припиняється, VPN-сервер Cisco AnyConnect відновлюється плавно, не вимагаючи ручного втручання. Cisco Meraki випустила оновлення програмного забезпечення, які усувають цю вразливість.**

### Запитання №1.3
Наведіть фрагменти прикладів уразливого програмного коду, розглянувши розділ References to Advisories, Solutions, and Tools.

CWE-234: невдала спроба обробити відсутній параметр
Якщо до функції надіслано занадто мало аргументів, функція все одно витягне очікувану кількість аргументів зі стеку. Потенційно, змінна кількість аргументів також може бути вичерпана у функції.

Наступний приклад демонструє слабкість. <p> <img width="386" alt="image" src="https://user-images.githubusercontent.com/52915030/209804720-10ba7020-df63-42f4-8cea-a2c687accf2b.png"></p>
Це може бути використано для розкриття інформації без будь-якої роботи. Фактично, кожен раз, коли ця функція запускається, вона друкуватиме наступні 4 байти в стеку після двох надісланих їй чисел.

### Запитання №2.1
Розшифруйте абревіатурну назву криптографічного алгоритму та режиму шифрування та вкажіть роки їх створення.

bf-ecb - Blowfish algorithm in ECB (Electronic CodeBook)
**Blowfish — криптографічний алгоритм, який реалізує блочне симетричне шифрування.
Розроблений Брюсом Шнайєром в 1993 році. Являє собою шифр на основі мережі Фейстеля. Виконано на простих і швидких операціях: XOR, підстановка, додавання. Не запатентований і вільно поширюваний.**

**Режим електронної книги кодів (англ. electronic codebook, ECB), він же режим простої заміни є найпростішим з режимів шифрування. Повідомлення розбивається на блоки і кожен блок шифрується окремо.**

### Запитання №2.2
Опишіть переваги та недоліки криптографічного алгоритму

Переваги: 

- Швидше, ніж інші алгоритми шифрування, такі як стандарт шифрування даних (DES)
- Blowfish є незапатентованим і безкоштовним для використання. Це означає, що будь-хто може використовувати Blowfish для будь-яких цілей
- Алгоритм Blowfish також має меншу кількість операцій для виконання порівняно з іншими алгоритмами шифрування
- Ключовий розклад Blowfish займає багато часу, але це може бути вигідно, оскільки атаки грубою силою є складнішими

Недоліки:

- Розклад ключа Blowfish займає багато часу, еквівалентно шифруванню 4 КБ даних, що може бути недоліком або перевагою. З боку недоліків, це займає дуже багато часу
- Невеликий розмір блоку Blowfish означає, що можуть відбуватися атаки Birthday Attack і скомпрометувати алгоритм шифрування.
- За ним йде Twofish, який був створений замість Blowfish, оскільки він кращий у більшості аспектів

### Запитання №2.3
Опишіть переваги та недоліки режиму шифрування.

Найбільш очевидною перевагою використання режиму ECB є його спрощеність. Інша основна перевага полягає в тому, що ECB може терпіти втрату блоків, не впливаючи на інші доступні блоки. Ця перевага актуальна у випадку, коли блоки надсилаються через мережу як пакети. Ця стійкість стала можливою завдяки тому факту, що будь-який блок Bi не залежить від жодного з його суміжних блоків.

Незважаючи на його переваги, до ECB ставляться зневажливо через те, що алгоритм шифрування є повністю детермінованим. Простіше кажучи, ідентичні блоки матимуть однакові шифри в режимі ECB, що може виявити шаблони, які мають блоки; тому ECB не повністю приховує свої деталі. Це загроза безпеці для його користувачів.

**Comment by oleksandrblazhko** [comment]
Оцінка = 7 балів.
Дякую за вашу активність!
