### ISSUE TITLE
CW9 - Variant 10

### ISSUE THREAD

**Issue by WeisseKatze** [oleksandrblazhko/ai181-lavrenova#32]
### Запитання №1.1
Опишіть ПЗ або програму бібліотеку, в яких знайдено вразливість:

- назва ПЗ або програмної бібліотеки, URL-посилання в інтернеті (знайти через пошукову систему): Western Digital My Cloud https://www.westerndigital.com/en-ap/support/software/my-cloud-os

- призначення ПЗ або програмної бібліотеки та приклади споживачів, які можуть бути зацікавлені у їх використанні: Хмарна платформа для зберігання файлів, доступ до яких можуть мати декілька користувачів. Користуватися платформою можна для приватних потреб людей, наприклад для зберігання сімейних фото, відео, музики. По суті це аналог Google Drive.

### Запитання №1.2
Опишіть знайдену вразливість , переклавшу на українську мову розділ Description.

Уразливість неправильної автентифікації в зашифрованих томах і функціях автоматичного монтування пристроїв Western Digital My Cloud дозволяє незахищений прямий доступ до інформації про диск у разі скидання пристрою. Ця проблема стосується: версії Western Digital My Cloud My Cloud до 5.25.124 у Linux.

### Запитання №1.3
Наведіть фрагменти прикладів уразливого програмного коду, розглянувши розділ References to Advisories, Solutions, and Tools.

CWE-287: неправильна автентифікація
Коли актор стверджує, що має певну особу, програмне забезпечення не доводить або недостатньо доводить, що твердження є правильним.

Наступний код має на меті переконатися, що користувач уже ввійшов у систему. Якщо ні, код виконує автентифікацію за допомогою наданого користувачем імені користувача та пароля. У разі успіху він встановлює файли cookie для входу в систему та користувача так, щоб вони «запам’ятовували», що користувач уже ввійшов. Нарешті, код виконує завдання адміністратора, якщо користувач, який увійшов у систему, має ім’я користувача «Адміністратор», як це записано в файлі cookie користувача.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/52915030/209952462-f929d271-5f72-4909-9076-60dfafbc6a77.png">

На жаль, цей код можна обійти. Зловмисник може встановити файли cookie самостійно, щоб код не перевіряв ім'я користувача та пароль. Зловмисник може зробити це за допомогою HTTP-запиту, що містить такі заголовки, як:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/52915030/209952513-fad330ee-4731-468b-94fc-9c484f68c782.png">

Встановлюючи для файлу cookie loggedin значення «true», зловмисник обходить всю перевірку автентифікації. Використовуючи значення «Адміністратор» у файлі cookie користувача, зловмисник також отримує привілеї для адміністрування програмного забезпечення.

### Запитання №2.1
Опишіть погрозу аутентифікації у вигляді історії взаємовідносин між зловмисником та користувачем.

Верифікатор запитує у користувача lookup secret. Користувач вводить значення секрету, яким володіє. Однак на його пристрої може бути несанкціоновано встановлений кейлоггер, таким чином зловмисник отримує повний доступ до сеансу автентифікації.

### Запитання №2.2
Надайте рекомендації щодо зниження ймовірності виникнення погрози аутентифікації.

Lookup secret потрібно використовувати лише один раз, Ця вимога має на меті гарантувати, що зловмисник із повним доступом до сеансу автентифікації (наприклад, реєстратор ключів) не зможе використовувати вихідні дані автентифікатора в майбутньому.

**Comment by oleksandrblazhko** [comment]
Оцінка = 5 балів.
Дякую за вашу активність!
